spring:
  application:
    name: whm-ai-code-mother-backend

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whm_ai_code_mother
    username: root
    password: WHM19990504

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.whm.whmaicodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

